export enum CALLBACK_COMMAND {
  listCategories,
  showState,
  createCategory,
  selectCategory,
  createCategoryCancel,
  editCategory,
  editCategoryCancel,
  deleteCategory,
  deleteCategoryCancel,
  deleteCategoryConfirm,
  addCard,
  addCardCancel,
  addCardEmptyAnswer,
  editCardQuestion,
  editCardQuestionCancel,
  editCardAnswer,
  deleteCard,
  deleteCardCancel,
  deleteCardConfirm,
  showNextCard,
  showAnswer,
  markAnswer,
}

// export enum CALLBACK_COMMAND {
//   listCategories = 'listCategories',
//   showState = 'showState',
//   createCategory = 'createCategory',
//   selectCategory = 'selectCategory',
//   createCategoryCancel = 'createCategoryCancel',
//   editCategory = 'editCategory',
//   editCategoryCancel = 'editCategoryCancel',
//   deleteCategory = 'deleteCategory',
//   deleteCategoryCancel = 'deleteCategoryCancel',
//   deleteCategoryConfirm = 'deleteCategoryConfirm',
//   addCard = 'addCard',
//   addCardCancel = 'addCardCancel',
//   addCardEmptyAnswer = 'addCardEmptyAnswer',
//   editCardQuestion = 'editCardQuestion',
//   editCardQuestionCancel = 'editCardQuestionCancel',
//   editCardAnswer = 'editCardAnswer',
//   deleteCard = 'deleteCard',
//   deleteCardCancel = 'deleteCardCancel',
//   deleteCardConfirm = 'deleteCardConfirm',
//   showNextCard = 'showNextCard',
//   showAnswer = 'showAnswer',
//   markAnswer = 'markAnswer',
// }
