export const COMMANDS = {
  createCategory: 'cmd_create_category',
  cancelCategoryCreation: 'cmd_create_category_cancel',
  selectCategory: 'cmd_select_category_',
  selectLanguage: 'cmd_select_language_',
  cancelCardCreation: 'cmd_create_card_cancel',
  changeCategory: 'cmd_change_category',
  setAnswer: 'cmd_set_answer',
  skipCard: 'cmd_skip_card',
  showAnswer: 'cmd_show_answer',
  markAnswer: 'cmd_mark_answer',
  startLearning: 'cmd_start_learning',
  addCard: 'cmd_add_card',
  deleteCategory: 'cmd_delete_category',
  deleteCategoryConfirm: 'cmd_delete_category_confirm',
  deleteCategoryCancel: 'cmd_delete_category_cancel',
};
